- hosts: all
  become: true
  gather_facts: false

  tasks:
      
    - name: Set timezone to Asia/Almaty
      community.general.timezone:
        name: Asia/Almaty  

    - name: Update apt cache
      apt: 
        update_cache: yes
    
    - name: Install System Utilites
      apt: 
        name: ['mc', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        state: present

    - name: Install yggdrasil
      apt:
        name: ['yggdrasil']
        state: present
      register: yggdrasil_install  
    
    - name: ensure file exists
      copy:
        content: ""
        dest: /vagrant/yggdrasil.conf
        force: no
        group: sys
        owner: root
      register: yggdrasil_config_exist
      when: yggdrasil_install.changed
    
    - name: Change yggdrasil config path
      community.general.ini_file:
        path: /lib/systemd/system/yggdrasil.service
        section: Service
        option: ExecStart
        value: "/usr/sbin/yggdrasil -useconffile /vagrant/yggdrasil.conf"
        state: present
    
    - name: Start service yggdrasil after vagrant shared folder mounted
      community.general.ini_file:
        path: /lib/systemd/system/yggdrasil.service
        section: Unit
        option: After
        value: "network-online.target vagrant.mount"
        state: present
    
    - name: Generate yggdrasil conf
      shell: yggdrasil -genconf > /vagrant/yggdrasil.conf
      when: yggdrasil_config_exist.changed

    - name: Enable service yggdrasil
      service:
         name: yggdrasil
         enabled: yes
         state: started
         
    - name: Install Dante
      apt:
        name: ['dante-server']
        state: present        
      
    - name: Configure templates
      template: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {src: "templates/danted.conf", dest: "/etc/danted.conf"} 
      
    - name: Enable service danted
      service:
         name: danted
         enabled: yes
         state: stopped    
         
    - name: Start service danted after yggdrasil
      community.general.ini_file:
        path: /lib/systemd/system/danted.service
        section: Unit
        option: After
        value: "yggdrasil.service"
        state: present 
    
    - name: Enable service danted
      service:
         name: danted
         enabled: yes
         state: started